#!/usr/bin/env python3
#

# Script cats stdin to a file.  But only overwrites the file if the
# contents has changed.

import sys
import os


# Determine output name
ofname = sys.argv[1]

# Read all of stdin (new version of output file)
file1 = sys.stdin.buffer.read()

if os.path.exists(ofname):

    # Read all of the output file
    with open(ofname, 'rb') as fin:
        file0 = fin.read()

    # Compare to what we had
    if file0 == file1:
        print('Files the same, no change')
        sys.exit(0)


# Output file doesn't exist or differs; just write
with open(ofname, 'wb') as out:
    out.write(file1)


