#!/usr/bin/env python
#
# Script like ncdump, but converts time variables to Python datetimes.

from uafgi import earthdata
import sys
import argparse

parser = argparse.ArgumentParser(description='Dump CF Time variables in a NetCDF file')
parser.add_argument(
    '-f', '--force', action='store_true',
    help='Forced overwrite of existing files?')

parser.add_argument(
    '-q', '--quiet', action='store_true',
    help='Suppress messages?')

parser.add_argument(
    'urls', nargs='*',
    help='URLs to download')

args = parser.parse_args()

earthdata.cmr_download(args.urls, force=args.force, quiet=args.quiet)



